### ISSUE TITLE
karma-requirejs does not statisfy siblings peerDependencies

### ISSUE THREAD

**Issue by leszekhanusz** [sgentile/generator-nesa#1]
When running yo nesa:

npm ERR! peerinvalid The package karma-requirejs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma@0.10.10 wants karma-requirejs@~0.2.0

npm ERR! System Linux 3.11.0-18-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/leszek/yo/nesa/client
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/leszek/yo/nesa/client/npm-debug.log
npm ERR! not ok code 0

**Comment by sgentile** [comment]
can you try installing karma-requirejs@~0.2.0 and see if this resolves the issue?

**Comment by leszekhanusz** [comment]
Yes, it resolves the issue.
